apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpolar.fullname" . }}
  labels:
    {{- include "cpolar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: admin-console
      protocol: TCP
      name: admin-console
  selector:
    {{- include "cpolar.selectorLabels" . | nindent 4 }}
